services:
  - type: web
    name: arvr-insurance
    runtime: docker
    plan: free

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_URL
        value: https://arvr-insurance.onrender.com

      - key: APP_DEBUG
        value: false

      - key: DB_CONNECTION
        value: mongodb

      - key: LOG_CHANNEL
        value: stack

      # --- Secure AI Agent Variables ---
      - key: GROQ_API_KEY
        sync: false # Render dashboard UI will securely prompt you to insert this value

      - key: MONGO_URI
        fromEnvVar: MONGO_URI # This instructs Render to safely pull the value you already saved 